name: CreateAndTestRelease

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New PyMeshLab Version'
        required: true
        default: 'YYYY.MM'

env:
  QT_VERSION: 5.15.2

jobs:
  update_version:
    name: Update Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update PYML_VERSION
      run: |
        echo ${{ github.event.inputs.version }} | tr -d '\n'> PYML_VERSION
    - name: Commit change
      uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: Update PYML_VERSION to ${{ github.event.inputs.version }}

  # first, we build PyMeshLab
  build_pymeshlab:
    name: Build PyMeshLab
    runs-on: ${{ matrix.os }}
    needs: update_version
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]
        pyversion: [3.7, 3.8, 3.9, "3.10"]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
        submodules: recursive
    - name: Setup MSVC
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1
    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache-${{ env.QT_VERSION }}
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        version: ${{ env.QT_VERSION }}
    - name: Install Python ${{ matrix.pyversion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pyversion }}
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update && sudo apt-get upgrade
        sudo apt-get install -y mesa-common-dev libglu1-mesa-dev libgmp-dev libcgal-dev libboost-all-dev
        #needed by qt 5.15 on linux
        sudo apt-get install libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-render-util0-dev libxcb-xinerama0-dev
    - name: Install MacOS dependencies
      if: runner.os == 'macOS'
      run: |
        brew install libomp cgal xerces-c
    - name: Install Windows dependencies
      if: runner.os == 'Windows'
      run: |
        echo "name=VCINSTALLDIR::C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\VC" >> $GITHUB_ENV
        $env:PATH = "${{ env.PATH }};C:\msys64\mingw64\bin;C:\msys64\usr\bin"
        pacman.exe -S --noconfirm --noprogressbar wget unzip
    - name: Environment variables
      id: envs
      shell: bash
      run: |
        cd src/meshlab
        echo  ::set-output name=meshlab_commit::$(git rev-parse --short HEAD)
    - name: Download external libraries
      if: runner.os == 'Windows'
      shell: C:\shells\msys2bash.cmd {0}
      run: |
        bash src/meshlab/scripts/${{ runner.os }}/0_download_ext.sh
    - name: Build PyMeshLab ${{ matrix.pyversion }}
      shell: bash
      run: |
        sh scripts/${{ runner.os }}/1_build.sh
    - name: Deploy PyMeshLab ${{ matrix.pyversion }}
      shell: bash
      run: |
        sh scripts/${{ runner.os }}/2_deploy.sh -qt=${{ env.Qt5_DIR }}
    - name: Build Wheel
      shell: bash
      run: |
       pip install wheel
       pip wheel . -w wheels/
    - name: Upload PyMeshLab_${{ runner.os }}_python${{ matrix.pyversion }}
      uses: actions/upload-artifact@v2
      with:
        name: PyMeshLab_${{ runner.os }}_python${{ matrix.pyversion }}
        path: pymeshlab
    - name: Upload wheel ${{ runner.os }} python ${{ matrix.pyversion }}
      uses: actions/upload-artifact@v2
      with:
        name: pymeshlab_whl_${{ runner.os }}_python${{ matrix.pyversion }}
        path: wheels/pymeshlab*.whl

  # we test the zip package ...
  package_test:
    name: Test PyMeshLab
    runs-on: ${{ matrix.os }}
    needs: build_pymeshlab
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        pyversion: [3.7, 3.8, 3.9, "3.10"]
    steps:
    - name: Download PyMeshLab_${{ runner.os }}_python${{ matrix.pyversion }}
      uses: actions/download-artifact@v2
      with:
        name: PyMeshLab_${{ runner.os }}_python${{ matrix.pyversion }}
        path: pymeshlab/
    - name: Install Python ${{ matrix.pyversion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pyversion }}
    - name: Run Tests ${{ matrix.pyversion }}
      if: runner.os == 'macOS'
      run: |
        pip3 install pytest numpy
        pytest --pyargs pymeshlab
    - name: Run Tests ${{ matrix.pyversion }}
      if: runner.os != 'macOS'
      run: |
        pip3 install pytest numpy
        python -c 'import pymeshlab; pymeshlab.use_cpu_opengl()' #just for windows
        pytest --pyargs pymeshlab -m "not glcontext"

  # ... and the wheel
  wheel_test:
    name: Test Wheel
    needs: build_pymeshlab
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        pyversion: [3.7, 3.8, 3.9, "3.10"]
    steps:
    - name: Download pymeshlab_whl_${{ runner.os }}_python${{ matrix.pyversion }}
      uses: actions/download-artifact@v2
      with:
        name: pymeshlab_whl_${{ runner.os }}_python${{ matrix.pyversion }}
        path: .
    - name: Install Python ${{ matrix.pyversion }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pyversion }}
    - name: Install and Test Wheel
      if: runner.os == 'macOS'
      shell: bash
      run: |
        pip install pytest
        pip install pymeshlab*.whl
        pytest --pyargs pymeshlab
    - name: Install and Test Wheel
      if: runner.os != 'macOS'
      shell: bash
      run: |
        pip install pytest
        pip install pymeshlab*.whl
        python -c 'import pymeshlab; pymeshlab.use_cpu_opengl()' #just for windows
        pytest --pyargs pymeshlab -m "not glcontext"

  # after building and testing PyMeshLab for the three platforms, we create a release in github
  create_release:
    name: Create Release
    needs: [package_test, wheel_test]
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Publish Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.version }}
        release_name: 'PyMeshLab v${{ github.event.inputs.version }}'
        draft: false
        prerelease: false

  # then, we will upload all the artifacts to the release
  upload_release:
    name: Upload Release
    needs: [create_release]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [Linux, macOS, Windows]
        pyversion: [3.7, 3.8, 3.9, "3.10"]
    steps:
    #download zip package
    - name: Download PyMeshLab_${{ matrix.os }}_python${{ matrix.pyversion }}
      uses: actions/download-artifact@v1
      with:
        name: PyMeshLab_${{ matrix.os }}_python${{ matrix.pyversion }}
        path: pymeshlab/
    - name: Create PyMeshLab Archive
      run: |
        cd pymeshlab
        zip -r ../PyMeshLab_${{ matrix.os }}_python${{ matrix.pyversion }}.zip *
    #upload zip package
    - name: Upload PyMeshLab_${{ matrix.os }}_python${{ matrix.pyversion }}
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{needs.create_release.outputs.upload_url}}
        asset_path: PyMeshLab_${{ matrix.os }}_python${{ matrix.pyversion }}.zip
        asset_name: PyMeshLab_${{ matrix.os }}_python${{ matrix.pyversion }}.zip
        asset_content_type: PyMeshLab ${{ matrix.pyversion }}
    #download wheel
    - name: Download pymeshlab_whl_${{ matrix.os }}_python${{ matrix.pyversion }}
      uses: actions/download-artifact@v2
      with:
        name: pymeshlab_whl_${{ matrix.os }}_python${{ matrix.pyversion }}
        path: .
    - name: Get Wheel Name
      id: wheel_name
      shell: bash
      run: |
        NAME=$(ls -d pymeshlab*.whl)
        echo  ::set-output name=wname::$(ls -d pymeshlab*.whl)
    #upload wheel
    - name: Upload Wheel to Release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{needs.create_release.outputs.upload_url}}
        asset_path: ${{steps.wheel_name.outputs.wname}}
        asset_name: ${{steps.wheel_name.outputs.wname}}
        asset_content_type: PyMeshLab ${{ matrix.pyversion }}
